/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import estacionamento.Carro;
import estacionamento.CatalogoDeCarros;
import estacionamento.CatalogoDeVagas;
import static estacionamento.Estacionamento.catalogoDeCarros;
import static estacionamento.Estacionamento.catalogoDeVagas;
import estacionamento.Estatistica;
import estacionamento.Vaga;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wagner
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    CatalogoDeCarros catalogoDeCarros = new CatalogoDeCarros ();
    CatalogoDeVagas catalogoDeVagas = new CatalogoDeVagas ();
    Estatistica estatistica = new Estatistica ();

    /**
     * Creates new form TelaPrincipal
     * @param continuar
     */
    public TelaPrincipal(boolean continuar) throws IOException {
        initComponents();
        
        if (continuar == true) { //continuar simulação
            carregar ();
        }
        else { //iniciar nova simulação
            iniciar ();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrarNaGaragem = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSairDaGaragem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnEncerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCarros = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVagas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Estacionamento");
        setResizable(false);

        btnEntrarNaGaragem.setText("Entrar");
        btnEntrarNaGaragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarNaGaragemMouseClicked(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");

        btnSairDaGaragem.setText("Sair");

        btnSalvar.setText("Salvar");

        btnRelatorio.setText("Relatório");

        btnEncerrar.setText("Encerrar");
        btnEncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncerrarMouseClicked(evt);
            }
        });

        tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Chassi", "Peso", "Altura", "Comprimento", "Largura"
            }
        ));
        jScrollPane2.setViewportView(tabelaCarros);

        tabelaVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificação", "Peso Máx", "Altura Máx", "Comprimento Máx", "Largura Máx"
            }
        ));
        jScrollPane1.setViewportView(tabelaVagas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntrarNaGaragem)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSairDaGaragem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelatorio)
                        .addGap(30, 30, 30)
                        .addComponent(btnEncerrar)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarNaGaragem)
                    .addComponent(btnPesquisar)
                    .addComponent(btnSairDaGaragem)
                    .addComponent(btnSalvar)
                    .addComponent(btnRelatorio)
                    .addComponent(btnEncerrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncerrarMouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_btnEncerrarMouseClicked

    private void btnEntrarNaGaragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarNaGaragemMouseClicked
        // TODO entrar na garagem
        TelaEntrarNaGaragem telaEntrarNaGaragem;
        telaEntrarNaGaragem = new TelaEntrarNaGaragem();
        telaEntrarNaGaragem.setVisible(true);
    }//GEN-LAST:event_btnEntrarNaGaragemMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JButton btnEntrarNaGaragem;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSairDaGaragem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaCarros;
    private javax.swing.JTable tabelaVagas;
    // End of variables declaration//GEN-END:variables

    public void iniciar () throws IOException{
        System.out.println("Iniciando nova simulação!");
        catalogoDeCarros.carregaCatalogoDoArquivo("VEICULOS.txt");
        catalogoDeVagas.carregaCatalogoDoArquivo("VAGAS.txt");
        System.out.println("Veículos e vagas carregados!");
        carregarTabelas ();
    }
    
    public void carregar () {
        
    }
    
    public void carregarTabelas () {
        Map <String, Carro> catalogoCarros;
        Map <String, Vaga> catalogoVagas;
        catalogoCarros = catalogoDeCarros.pegarCatalogo();
        catalogoVagas = catalogoDeVagas.pegarCatalogo();
        
        DefaultTableModel valoresCarros = (DefaultTableModel) tabelaCarros.getModel();
        for (Carro carro: catalogoCarros.values()) {
            if (!carro.pegaSituacao()) {
                valoresCarros.addRow(new Object[] {carro.pegaModelo(), carro.pegaChassi(), carro.pegaPeso(),
                                            carro.pegaAltura(), carro.pegaComprimento(), carro.pegaLargura()});
            }
        }
        
        DefaultTableModel valoresVagas = (DefaultTableModel) tabelaVagas.getModel();
        for (Vaga vaga: catalogoVagas.values()) {
            if (!vaga.pegaDisponibilidade()) {
                valoresVagas.addRow(new Object[] {vaga.pegaIdentificacao(), vaga.pegaPesoMaximo(), vaga.pegaAlturaMaxima(),
                                                vaga.pegaComprimentoMaximo(), vaga.pegaLarguraMaxima()});
            }
        }
        
        System.out.println (catalogoDeCarros.pegaModelo(1244));
    }
}
